### ISSUE TITLE
Add russian translation to the mod (*game not required!*)

### ISSUE THREAD

**Issue by ctcDNightmare** [ctcDNightmare/avorion-scrapyardplus#30]
Currently the mod only includes english texts and the german translations for them.

The core game supports russian as well and the mod would need someone who knows the language to translate the couple of texts it uses.

[This](https://github.com/ctcDNightmare/avorion-scrapyardplus/blob/develop/src/data/localization/deutsch.po) is the german version as reference which also includes the original strings in english.

If you want to help, feel free to:
- copy the german file
- rename it to ```ru.po``` inside the current localization folder
- translate all the (very similar, I know) texts in there. 
*First line is the original in english, second line would be the translated version in target language*

**Comment by OleksiyRudenko** [comment]
Hi @ctcDNightmare can I help you with this?
I could add Ukrainian translation as well.

**Comment by ctcDNightmare** [comment]
@OleksiyRudenko sure you can help me with this. For Ukranian I'm not sure, I don't think the base game supports that language so only the russian part would be needed.
Just drop me a pull-request once you've had the time to look into it.

Sorry for the late reply, was on vacation.

**Comment by OleksiyRudenko** [comment]
@ctcDNightmare just to make sure that I understand the roles of string template formatting tokens (I am not really good at Lua). It might be important for grammatical cases. I would try to reword phrases so that der Nominativ fits the phrase construction.

In phrases like `Your %s salvaging license in %s will run out in %s...` first `%s` stands for an alliance name and the second `%s` stands for a period of time, right?

An example of complete message might help.

In the phrase of `Oh look, a %s wreck just got dropped off at my Scrapyard!` does `%s` stand for a ship type (Battleship, Dreadnought, Destroyer etc) or for a ship's proper name that might be of any grammatical gender?

An example of complete message might help.

Thank you
